import Footer from '@/components/common/Footer';
import Navbar from '@/components/common/Navbar';
import Head from 'next/head';
import React from 'react'

const Default = (props) => {
  return (
    <>
    <Head>
        <title>OpensoftTech | Build Your Thoughts.</title>
        <meta charset="utf-8" />
        <meta name="google-site-verification" content="6E3-B9C7zn9zWLUcSF3dOU6nWwX23qS-OUAeXDAL9z4" />
        <meta name="description" content="Generated by create next app" />
        <meta name="og:title" content="OpensoftTech – We build your thoughts."></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="alternate icon" href="../favicon.ico"/>
      </Head>
      <main>
        <Navbar/>
        {props.children}
        <Footer/>
      </main>
    </>
  )
}

export default Default