name: Deploy Site

on:
  push:
    branches:
      - main
      - stage
      - dev
      - '*'

  workflow_dispatch:
    inputs:
      branch:
        description: "Desired Branch Name to Pull Code - main|stage|dev|"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Fetch Github Access Token
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Setup Node Environment (14.x)
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: |
          git checkout ${{ github.event.inputs.branch }}

      - name: Cache node Modules
        uses: actions/cache@v2
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}

      - name: Install  npm Packages
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
          
      - name: Build Site
        run: |
            npm run generate;

      - name: Configure AWS cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync from `dist` Directory to s3 Bucket
        run: |
          aws s3 sync dist/ s3://${{ secrets.BUCKET_NAME }}/site --acl public-read --exclude "*.map"
          echo cloudfront invalidation
          aws cloudfront create-invalidation \
           --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths '/site/*'
